cabal-version:   3.12
name:            sandbox
version:         0.1.0.0
license:         NONE
author:          Unknown
maintainer:      Unknown
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  MyLib
    build-depends:    base ^>=4.18.3.0
    hs-source-dirs:   lib
    default-language: Haskell2010

executable sandbox
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base ^>=4.18.3.0,
        sandbox

    hs-source-dirs:   exe
    default-language: Haskell2010

test-suite sandbox-test
    import:           warnings
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   tdd
    main-is:          Main.hs
    build-depends:
        base ^>=4.18.3.0,
        sandbox
