cabal-version:        3.12
name:                 sandbox
version:              0.1.0.0
license:              NONE
author:               Unknown
maintainer:           Unknown
build-type:           Simple
extra-doc-files:      CHANGELOG.md

common settings

    ghc-options:      -Wall
    default-language: Haskell2010
    build-depends:    base ^>=4.18.3.0

library

    import:           settings
    exposed-modules:  MyLib
    hs-source-dirs:   lib

executable sandbox

    import:           settings
    main-is:          Main.hs
    build-depends:
        bytestring,
        serialise,
        sandbox

    hs-source-dirs:   exe

test-suite sandbox-test

    import:           settings
    type:             exitcode-stdio-1.0
    hs-source-dirs:   tdd
    main-is:          Main.hs
    other-modules:    LazyByteString
    build-depends:    QuickCheck
                      , sandbox
